import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutProvider from "@/components/layoutProvider/LayoutProvider";
import Toast from "@/utlis/toast";
import { QueryClientProvider, useQueryClient } from "@tanstack/react-query";
import QueryProvider from "./providers/QueryProvider";
import Provider from "@/utlis/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}        
        `}
      >
        <Provider session={session}>
          <Toast />
          <QueryProvider>{children}</QueryProvider>
        </Provider>
      </body>
    </html>
  );
}
